name: dart_vlc_example
description: Demonstrates how to use the dart_vlc plugin.
publish_to: "none"

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter
  dart_vlc:
    path: ../
  flutter_portal: ^1.1.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
