name: dart_vlc
description: Flutter audio / video playback, broadcast & recording library for Windows & Linux. Based on libvlc.
version: 0.4.0
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md
publish_to: none

environment:
  sdk: 3.8.1
  flutter: 3.32.7

dependencies:
  flutter:
    sdk: flutter
  dart_vlc_ffi:
    path: ./ffi
  path: 1.9.1
  audio_video_progress_bar: 2.0.3

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  # No platform channel implementation after migration to FFI.
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
